services:
  - type: web
    name: marketplace-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn marketplace.marketplace.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DJANGO_SETTINGS_MODULE
        value: marketplace.marketplace.settings
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://marketplace-frontend.onrender.com

  - type: web
    name: marketplace-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://marketplace-backend.onrender.com

databases:
  - name: marketplace-db
    databaseName: marketplace
    user: marketplace
    plan: free 