services:
  - type: web
    name: my-django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn marketplace.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: marketplace.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
